name: torch
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python
  - numpy
  - scikit-learn
  - scipy
  - seaborn
  - pytorch
  - matplotlib
  - pandas
  - pip:
    - torchvision